CREATE OR REPLACE FUNCTION	chk_age_employee()	
RETURNS TRIGGER AS
$$
BEGIN			
		IF AGE(NEW.bdate, CURRENT_DATE) < INTERVAL '18 years' THEN			
				RAISE	EXCEPTION	'Underage alert'
		END IF;	
		RETURN NEW;
END;
$$	LANGUAGE	plpgsql;